using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using psms.Domain.Academic.Entities;
using psms.Domain.Shared.Enums;

namespace psms.Domain.Financial.Entities
{
    /// <summary>
    /// Represents a payment made by a parent for a student
    /// </summary>
    [Table("Payments")]
    public class Payment : FullAuditedEntity<Guid>, IMayHaveTenant, ISoftDelete
    {
        public const int MaxCurrencyLength = 10;
        public const int MaxReferenceLength = 100;
        public const int MaxReceiptNumberLength = 50;
        public const int MaxNotesLength = 2000;
        public const int MaxConcurrencyStampLength = 40;

        /// <summary>
        /// Tenant identifier for multi-tenancy
        /// </summary>
        public int? TenantId { get; set; }

        /// <summary>
        /// Student the payment is for
        /// </summary>
        [Required]
        public Guid StudentId { get; set; }

        /// <summary>
        /// Parent who made the payment
        /// </summary>
        [Required]
        public Guid ParentId { get; set; }

        /// <summary>
        /// Total amount of the payment
        /// </summary>
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Currency code (default ZAR for South Africa)
        /// </summary>
        [Required]
        [StringLength(MaxCurrencyLength)]
        public string Currency { get; set; }

        /// <summary>
        /// Method of payment used
        /// </summary>
        [Required]
        public SouthAfricanPaymentMethod PaymentMethod { get; set; }

        /// <summary>
        /// Date when payment was made
        /// </summary>
        [Required]
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// External payment reference (bank reference, gateway ID, etc.)
        /// </summary>
        [StringLength(MaxReferenceLength)]
        public string PaymentReference { get; set; }

        /// <summary>
        /// Unique receipt number generated by the system
        /// </summary>
        [Required]
        [StringLength(MaxReceiptNumberLength)]
        public string ReceiptNumber { get; set; }

        /// <summary>
        /// Current status of the payment
        /// </summary>
        [Required]
        public PaymentStatus Status { get; set; }

        /// <summary>
        /// Additional notes about the payment
        /// </summary>
        [StringLength(MaxNotesLength)]
        public string Notes { get; set; }

        /// <summary>
        /// Concurrency stamp for optimistic locking
        /// </summary>
        [StringLength(MaxConcurrencyStampLength)]
        public string ConcurrencyStamp { get; set; }

        /// <summary>
        /// Soft delete flag
        /// </summary>
        public bool IsDeleted { get; set; }

        // Navigation Properties
        [ForeignKey(nameof(StudentId))]
        public virtual Student Student { get; set; }

        [ForeignKey(nameof(ParentId))]
        public virtual Parent Parent { get; set; }

        // Collections
        public virtual ICollection<PaymentAllocation> PaymentAllocations { get; set; }

        /// <summary>
        /// Protected constructor for EF Core
        /// </summary>
        protected Payment()
        {
            PaymentAllocations = new HashSet<PaymentAllocation>();
            Currency = "ZAR";
        }

        /// <summary>
        /// Public constructor with required parameters
        /// </summary>
        public Payment(
            Guid id,
            int? tenantId,
            Guid studentId,
            Guid parentId,
            decimal amount,
            SouthAfricanPaymentMethod paymentMethod,
            string receiptNumber) : this()
        {
            Id = id;
            TenantId = tenantId;
            StudentId = studentId;
            ParentId = parentId;
            Amount = amount;
            PaymentMethod = paymentMethod;
            ReceiptNumber = receiptNumber;
            PaymentDate = DateTime.UtcNow;
            Status = PaymentStatus.Pending;
            IsDeleted = false;
            ConcurrencyStamp = Guid.NewGuid().ToString("N");
        }

        /// <summary>
        /// Gets the formatted amount with currency
        /// </summary>
        public string GetFormattedAmount()
        {
            return $"{Currency} {Amount:N2}";
        }

        /// <summary>
        /// Gets the total allocated amount
        /// </summary>
        public decimal GetTotalAllocated()
        {
            decimal total = 0;
            foreach (var allocation in PaymentAllocations)
            {
                total += allocation.Amount;
            }
            return total;
        }

        /// <summary>
        /// Gets the unallocated amount
        /// </summary>
        public decimal GetUnallocatedAmount()
        {
            return Amount - GetTotalAllocated();
        }

        /// <summary>
        /// Marks the payment as completed
        /// </summary>
        public void MarkAsCompleted()
        {
            if (Status == PaymentStatus.Completed)
                throw new InvalidOperationException("Payment is already completed.");

            Status = PaymentStatus.Completed;
        }

        /// <summary>
        /// Marks the payment as failed
        /// </summary>
        public void MarkAsFailed()
        {
            if (Status == PaymentStatus.Completed)
                throw new InvalidOperationException("Cannot mark a completed payment as failed.");

            Status = PaymentStatus.Failed;
        }

        /// <summary>
        /// Refunds the payment
        /// </summary>
        public void Refund()
        {
            if (Status != PaymentStatus.Completed)
                throw new InvalidOperationException("Only completed payments can be refunded.");

            Status = PaymentStatus.Refunded;
        }

        /// <summary>
        /// Cancels the payment
        /// </summary>
        public void Cancel()
        {
            if (Status == PaymentStatus.Completed || Status == PaymentStatus.Refunded)
                throw new InvalidOperationException("Cannot cancel a completed or refunded payment.");

            Status = PaymentStatus.Cancelled;
        }
    }
}
